### ISSUE TITLE
如何给根分区扩容

### ISSUE THREAD

**Issue by taoqys** [LordPenguin666/Arch-Linux-N1#2]
你好，我刷入了最新的6.25版内核的镜像到u盘使用，目前使用基本没有问题，但是根分区仅有2.5g，我尝试通过cfdisk更改分区大小，成功更改后并没有效果，使用df命令查看根分区依旧是2.5g，且无法安装较大的软件。
我尝试过重启，但并没有效果

**Comment by LordPenguin666** [comment]
没遇到这个问题, 你是用什么工具写入的

**Comment by taoqys** [comment]
我电脑不在身边，用的是Android上的etchdroid这个软件写入的，是否与此有关呢，若是的话我就过段时间再试试吧

**Comment by LordPenguin666** [comment]
用 https://www.balena.io/etcher 试试
